# Generated by Django 2.1.3 on 2019-01-09 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vtex_invoiced_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='stock_system.Order'),
        ),
    ]
