# Generated by Django 2.1.3 on 2019-01-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_system', '0002_auto_20190109_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method_group',
            field=models.TextField(default='migrate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='image_link',
            field=models.TextField(default='migrate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='stock_warehouse',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
