# Generated by Django 2.1.3 on 2019-01-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_system', '0003_auto_20190122_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='invoiced_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
