# Generated by Django 2.1.3 on 2019-02-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_system', '0005_order_vtex_paid_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='number',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='warehouse_position',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
